name: build and push 
on:
  push:
    branches:
      - main
jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: set up node
        uses: actions/setup-node@v2
        with:
         node-version: 17
      - name: install dependency
        run: npm install
      - name: login to docker hub
        uses: docker/actions@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USERNAME }}
      - name: build and push to docker hub
        uses: docker/build-push-actions@v2
        with:
          context: nodejs
          file: nodejs/Dockerfile
          pus: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nodeex:${{ github run_number }}

      - name: Docker logout
        run: docker logout
        
        
    
    
